'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="ossimob")>  _
Partial Public Class incidentDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
        MyBase.New(Global.One_Solution_Mobile.My.MySettings.Default.ossimobConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property lwmains() As System.Data.Linq.Table(Of lwmain)
		Get
			Return Me.GetTable(Of lwmain)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.lwmain")>  _
Partial Public Class lwmain
	
	Private _inci_id As String
	
	Private _agency As String
	
	Private _offense As String
	
	Private _complete As String
	
	Private _date_rept As System.Nullable(Of Date)
	
	Private _streetnbr As String
	
	Private _streetdir As String
	
	Private _street As String
	
	Private _apt_flr As String
	
	Private _city As String
	
	Private _state As String
	
	Private _zip As String
	
	Private _reportedas As String
	
	Private _hour_rept As String
	
	Private _date_occu As System.Nullable(Of Date)
	
	Private _hour_occu As String
	
	Private _dow1 As String
	
	Private _date_fnd As System.Nullable(Of Date)
	
	Private _hour_fnd As String
	
	Private _dow2 As String
	
	Private _tract As String
	
	Private _zone As String
	
	Private _district As String
	
	Private _reportarea As String
	
	Private _neighborhd As String
	
	Private _subdivisn As String
	
	Private _weather As String
	
	Private _premise As String
	
	Private _forcible As Char
	
	Private _weapon As String
	
	Private _weaponauto As Char
	
	Private _hatebias As String
	
	Private _category1 As String
	
	Private _category2 As String
	
	Private _name_id As Integer
	
	Private _offcr_id As Integer
	
	Private _emunit As String
	
	Private _emdivision As String
	
	Private _emsection As String
	
	Private _emshift As String
	
	Private _asst_offcr As Char
	
	Private _supervisor As Integer
	
	Private _recreview As String
	
	Private _csstatus As String
	
	Private _csstatusdt As System.Nullable(Of Date)
	
	Private _dispostn As String
	
	Private _datedispos As System.Nullable(Of Date)
	
	Private _narrative1 As String
	
	Private _supplement As String
	
	Private _investigtr As Integer
	
	Private _invststats As String
	
	Private _investunit As String
	
	Private _geox As Integer
	
	Private _geoy As Integer
	
	Private _lwnameflag As Char
	
	Private _domestic As String
	
	Private _storagea As String
	
	Private _storageb As String
	
	Private _creserve1 As String
	
	Private _nreserve1 As Integer
	
	Private _lwgrant As String
	
	Private _seculevel As Char
	
	Private _sysflag As String
	
	Private _addtime As System.Nullable(Of Date)
	
	Private _adduser As String
	
	Private _addconsole As String
	
	Private _yearstamp As Integer
	
	Private _monthstamp As Byte
	
	Private _oldcasenbr As String
	
	Private _exacestm As String
	
	Private _lightcond As String
	
	Private _lwcircum As String
	
	Private _creserve2 As String
	
	Private _creserve3 As String
	
	Private _labseized As Integer
	
	Private _gangrelat As String
	
	Private _ibr_date As System.Nullable(Of Date)
	
	Private _ibr_resend As Byte
	
	Private _reg_date As System.Nullable(Of Date)
	
	Private _reg_resend As Byte
	
	Private _rollcall As Boolean
	
	Private _schoolyr As String
	
	Private _locacode As String
	
	Private _locadesc As String
	
	Private _locaphone As String
	
	Private _buildarea As String
	
	Private _persinvst As Char
	
	Private _polijuris As String
	
	Private _assoccode As String
	
	Private _locatype As Char
	
	Private _schooltyp As String
	
	Private _falsealrm As Char
	
	Private _injurdesc As String
	
	Private _truancrel As Char
	
	Private _drugtype As Char
	
	Private _hrsrept As Char
	
	Private _hrsnotdt As System.Nullable(Of Date)
	
	Private _hrsnotby As Integer
	
	Private _sparrace As String
	
	Private _sparsex As Char
	
	Private _sparage As String
	
	Private _reccheck As Char
	
	Private _recperinvs As Char
	
	Private _recadmrev As Char
	
	Private _pedinj As Char
	
	Private _regioncode As Char
	
	Private _plantsecu As String
	
	Private _saorefdate As System.Nullable(Of Date)
	
	Private _eeoadate As System.Nullable(Of Date)
	
	Private _offcrasslt As Char
	
	Private _perinvrej As Char
	
	Private _eeeorej As Char
	
	Private _persuadrej As Char
	
	Private _spardate As System.Nullable(Of Date)
	
	Private _sparcaseid As String
	
	Private _sparweap As String
	
	Private _sparhrsby As Integer
	
	Private _age As String
	
	Private _race As String
	
	Private _sex As Char
	
	Private _cleryloc As String
	
	Private _followup As String
	
	Private _occdtunk As Boolean
	
	Private _lwmainid As Integer
	
	Private _mobnamekey As String
	
	Private _mobilekey As String
	
	Private _mobilepkey As String
	
	Private _mobstatus As String
	
	Private _mobstby As String
	
	Private _mobstdate As System.Nullable(Of Date)
	
	Private _mobileflag As Char
	
	Private _mobileid As String
	
	Private _moblastrev As String
	
	Private _mobnotes As String
	
	Private _mobunitid As String
	
	Private _mobsupgrp As String
	
	Private _supervsr2 As Integer
	
	Private _mobstdate2 As System.Nullable(Of Date)
	
	Private _suprevlvl As String
	
	Private _clerytyp As String
	
	Private _entry1 As String
	
	Private _exit1 As String
	
	Private _safecode As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_inci_id", DbType:="VarChar(12) NOT NULL", CanBeNull:=false)>  _
	Public Property inci_id() As String
		Get
			Return Me._inci_id
		End Get
		Set
			If (String.Equals(Me._inci_id, value) = false) Then
				Me._inci_id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_agency", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property agency() As String
		Get
			Return Me._agency
		End Get
		Set
			If (String.Equals(Me._agency, value) = false) Then
				Me._agency = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_offense", DbType:="VarChar(60) NOT NULL", CanBeNull:=false)>  _
	Public Property offense() As String
		Get
			Return Me._offense
		End Get
		Set
			If (String.Equals(Me._offense, value) = false) Then
				Me._offense = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_complete", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property complete() As String
		Get
			Return Me._complete
		End Get
		Set
			If (String.Equals(Me._complete, value) = false) Then
				Me._complete = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_date_rept", DbType:="DateTime")>  _
	Public Property date_rept() As System.Nullable(Of Date)
		Get
			Return Me._date_rept
		End Get
		Set
			If (Me._date_rept.Equals(value) = false) Then
				Me._date_rept = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_streetnbr", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property streetnbr() As String
		Get
			Return Me._streetnbr
		End Get
		Set
			If (String.Equals(Me._streetnbr, value) = false) Then
				Me._streetnbr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_streetdir", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property streetdir() As String
		Get
			Return Me._streetdir
		End Get
		Set
			If (String.Equals(Me._streetdir, value) = false) Then
				Me._streetdir = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_street", DbType:="VarChar(60) NOT NULL", CanBeNull:=false)>  _
	Public Property street() As String
		Get
			Return Me._street
		End Get
		Set
			If (String.Equals(Me._street, value) = false) Then
				Me._street = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apt_flr", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property apt_flr() As String
		Get
			Return Me._apt_flr
		End Get
		Set
			If (String.Equals(Me._apt_flr, value) = false) Then
				Me._apt_flr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_city", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property city() As String
		Get
			Return Me._city
		End Get
		Set
			If (String.Equals(Me._city, value) = false) Then
				Me._city = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_state", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property state() As String
		Get
			Return Me._state
		End Get
		Set
			If (String.Equals(Me._state, value) = false) Then
				Me._state = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_zip", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property zip() As String
		Get
			Return Me._zip
		End Get
		Set
			If (String.Equals(Me._zip, value) = false) Then
				Me._zip = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reportedas", DbType:="VarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property reportedas() As String
		Get
			Return Me._reportedas
		End Get
		Set
			If (String.Equals(Me._reportedas, value) = false) Then
				Me._reportedas = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hour_rept", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property hour_rept() As String
		Get
			Return Me._hour_rept
		End Get
		Set
			If (String.Equals(Me._hour_rept, value) = false) Then
				Me._hour_rept = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_date_occu", DbType:="DateTime")>  _
	Public Property date_occu() As System.Nullable(Of Date)
		Get
			Return Me._date_occu
		End Get
		Set
			If (Me._date_occu.Equals(value) = false) Then
				Me._date_occu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hour_occu", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property hour_occu() As String
		Get
			Return Me._hour_occu
		End Get
		Set
			If (String.Equals(Me._hour_occu, value) = false) Then
				Me._hour_occu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dow1", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property dow1() As String
		Get
			Return Me._dow1
		End Get
		Set
			If (String.Equals(Me._dow1, value) = false) Then
				Me._dow1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_date_fnd", DbType:="DateTime")>  _
	Public Property date_fnd() As System.Nullable(Of Date)
		Get
			Return Me._date_fnd
		End Get
		Set
			If (Me._date_fnd.Equals(value) = false) Then
				Me._date_fnd = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hour_fnd", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property hour_fnd() As String
		Get
			Return Me._hour_fnd
		End Get
		Set
			If (String.Equals(Me._hour_fnd, value) = false) Then
				Me._hour_fnd = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dow2", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property dow2() As String
		Get
			Return Me._dow2
		End Get
		Set
			If (String.Equals(Me._dow2, value) = false) Then
				Me._dow2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tract", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property tract() As String
		Get
			Return Me._tract
		End Get
		Set
			If (String.Equals(Me._tract, value) = false) Then
				Me._tract = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_zone", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property zone() As String
		Get
			Return Me._zone
		End Get
		Set
			If (String.Equals(Me._zone, value) = false) Then
				Me._zone = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_district", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property district() As String
		Get
			Return Me._district
		End Get
		Set
			If (String.Equals(Me._district, value) = false) Then
				Me._district = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reportarea", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property reportarea() As String
		Get
			Return Me._reportarea
		End Get
		Set
			If (String.Equals(Me._reportarea, value) = false) Then
				Me._reportarea = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_neighborhd", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property neighborhd() As String
		Get
			Return Me._neighborhd
		End Get
		Set
			If (String.Equals(Me._neighborhd, value) = false) Then
				Me._neighborhd = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_subdivisn", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property subdivisn() As String
		Get
			Return Me._subdivisn
		End Get
		Set
			If (String.Equals(Me._subdivisn, value) = false) Then
				Me._subdivisn = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_weather", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property weather() As String
		Get
			Return Me._weather
		End Get
		Set
			If (String.Equals(Me._weather, value) = false) Then
				Me._weather = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_premise", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property premise() As String
		Get
			Return Me._premise
		End Get
		Set
			If (String.Equals(Me._premise, value) = false) Then
				Me._premise = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_forcible", DbType:="Char(1) NOT NULL")>  _
	Public Property forcible() As Char
		Get
			Return Me._forcible
		End Get
		Set
			If ((Me._forcible = value)  _
						= false) Then
				Me._forcible = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_weapon", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property weapon() As String
		Get
			Return Me._weapon
		End Get
		Set
			If (String.Equals(Me._weapon, value) = false) Then
				Me._weapon = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_weaponauto", DbType:="Char(1) NOT NULL")>  _
	Public Property weaponauto() As Char
		Get
			Return Me._weaponauto
		End Get
		Set
			If ((Me._weaponauto = value)  _
						= false) Then
				Me._weaponauto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hatebias", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property hatebias() As String
		Get
			Return Me._hatebias
		End Get
		Set
			If (String.Equals(Me._hatebias, value) = false) Then
				Me._hatebias = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_category1", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property category1() As String
		Get
			Return Me._category1
		End Get
		Set
			If (String.Equals(Me._category1, value) = false) Then
				Me._category1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_category2", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property category2() As String
		Get
			Return Me._category2
		End Get
		Set
			If (String.Equals(Me._category2, value) = false) Then
				Me._category2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_name_id", DbType:="Int NOT NULL")>  _
	Public Property name_id() As Integer
		Get
			Return Me._name_id
		End Get
		Set
			If ((Me._name_id = value)  _
						= false) Then
				Me._name_id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_offcr_id", DbType:="Int NOT NULL")>  _
	Public Property offcr_id() As Integer
		Get
			Return Me._offcr_id
		End Get
		Set
			If ((Me._offcr_id = value)  _
						= false) Then
				Me._offcr_id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_emunit", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property emunit() As String
		Get
			Return Me._emunit
		End Get
		Set
			If (String.Equals(Me._emunit, value) = false) Then
				Me._emunit = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_emdivision", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property emdivision() As String
		Get
			Return Me._emdivision
		End Get
		Set
			If (String.Equals(Me._emdivision, value) = false) Then
				Me._emdivision = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_emsection", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property emsection() As String
		Get
			Return Me._emsection
		End Get
		Set
			If (String.Equals(Me._emsection, value) = false) Then
				Me._emsection = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_emshift", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property emshift() As String
		Get
			Return Me._emshift
		End Get
		Set
			If (String.Equals(Me._emshift, value) = false) Then
				Me._emshift = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_asst_offcr", DbType:="Char(1) NOT NULL")>  _
	Public Property asst_offcr() As Char
		Get
			Return Me._asst_offcr
		End Get
		Set
			If ((Me._asst_offcr = value)  _
						= false) Then
				Me._asst_offcr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_supervisor", DbType:="Int NOT NULL")>  _
	Public Property supervisor() As Integer
		Get
			Return Me._supervisor
		End Get
		Set
			If ((Me._supervisor = value)  _
						= false) Then
				Me._supervisor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_recreview", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property recreview() As String
		Get
			Return Me._recreview
		End Get
		Set
			If (String.Equals(Me._recreview, value) = false) Then
				Me._recreview = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_csstatus", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property csstatus() As String
		Get
			Return Me._csstatus
		End Get
		Set
			If (String.Equals(Me._csstatus, value) = false) Then
				Me._csstatus = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_csstatusdt", DbType:="DateTime")>  _
	Public Property csstatusdt() As System.Nullable(Of Date)
		Get
			Return Me._csstatusdt
		End Get
		Set
			If (Me._csstatusdt.Equals(value) = false) Then
				Me._csstatusdt = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dispostn", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property dispostn() As String
		Get
			Return Me._dispostn
		End Get
		Set
			If (String.Equals(Me._dispostn, value) = false) Then
				Me._dispostn = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_datedispos", DbType:="DateTime")>  _
	Public Property datedispos() As System.Nullable(Of Date)
		Get
			Return Me._datedispos
		End Get
		Set
			If (Me._datedispos.Equals(value) = false) Then
				Me._datedispos = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_narrative1", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property narrative1() As String
		Get
			Return Me._narrative1
		End Get
		Set
			If (String.Equals(Me._narrative1, value) = false) Then
				Me._narrative1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_supplement", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property supplement() As String
		Get
			Return Me._supplement
		End Get
		Set
			If (String.Equals(Me._supplement, value) = false) Then
				Me._supplement = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_investigtr", DbType:="Int NOT NULL")>  _
	Public Property investigtr() As Integer
		Get
			Return Me._investigtr
		End Get
		Set
			If ((Me._investigtr = value)  _
						= false) Then
				Me._investigtr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_invststats", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property invststats() As String
		Get
			Return Me._invststats
		End Get
		Set
			If (String.Equals(Me._invststats, value) = false) Then
				Me._invststats = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_investunit", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property investunit() As String
		Get
			Return Me._investunit
		End Get
		Set
			If (String.Equals(Me._investunit, value) = false) Then
				Me._investunit = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_geox", DbType:="Int NOT NULL")>  _
	Public Property geox() As Integer
		Get
			Return Me._geox
		End Get
		Set
			If ((Me._geox = value)  _
						= false) Then
				Me._geox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_geoy", DbType:="Int NOT NULL")>  _
	Public Property geoy() As Integer
		Get
			Return Me._geoy
		End Get
		Set
			If ((Me._geoy = value)  _
						= false) Then
				Me._geoy = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lwnameflag", DbType:="Char(1) NOT NULL")>  _
	Public Property lwnameflag() As Char
		Get
			Return Me._lwnameflag
		End Get
		Set
			If ((Me._lwnameflag = value)  _
						= false) Then
				Me._lwnameflag = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_domestic", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property domestic() As String
		Get
			Return Me._domestic
		End Get
		Set
			If (String.Equals(Me._domestic, value) = false) Then
				Me._domestic = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_storagea", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property storagea() As String
		Get
			Return Me._storagea
		End Get
		Set
			If (String.Equals(Me._storagea, value) = false) Then
				Me._storagea = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_storageb", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property storageb() As String
		Get
			Return Me._storageb
		End Get
		Set
			If (String.Equals(Me._storageb, value) = false) Then
				Me._storageb = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_creserve1", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property creserve1() As String
		Get
			Return Me._creserve1
		End Get
		Set
			If (String.Equals(Me._creserve1, value) = false) Then
				Me._creserve1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nreserve1", DbType:="Int NOT NULL")>  _
	Public Property nreserve1() As Integer
		Get
			Return Me._nreserve1
		End Get
		Set
			If ((Me._nreserve1 = value)  _
						= false) Then
				Me._nreserve1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lwgrant", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property lwgrant() As String
		Get
			Return Me._lwgrant
		End Get
		Set
			If (String.Equals(Me._lwgrant, value) = false) Then
				Me._lwgrant = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_seculevel", DbType:="Char(1) NOT NULL")>  _
	Public Property seculevel() As Char
		Get
			Return Me._seculevel
		End Get
		Set
			If ((Me._seculevel = value)  _
						= false) Then
				Me._seculevel = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sysflag", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property sysflag() As String
		Get
			Return Me._sysflag
		End Get
		Set
			If (String.Equals(Me._sysflag, value) = false) Then
				Me._sysflag = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_addtime", DbType:="DateTime")>  _
	Public Property addtime() As System.Nullable(Of Date)
		Get
			Return Me._addtime
		End Get
		Set
			If (Me._addtime.Equals(value) = false) Then
				Me._addtime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_adduser", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property adduser() As String
		Get
			Return Me._adduser
		End Get
		Set
			If (String.Equals(Me._adduser, value) = false) Then
				Me._adduser = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_addconsole", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property addconsole() As String
		Get
			Return Me._addconsole
		End Get
		Set
			If (String.Equals(Me._addconsole, value) = false) Then
				Me._addconsole = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_yearstamp", DbType:="Int NOT NULL")>  _
	Public Property yearstamp() As Integer
		Get
			Return Me._yearstamp
		End Get
		Set
			If ((Me._yearstamp = value)  _
						= false) Then
				Me._yearstamp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_monthstamp", DbType:="TinyInt NOT NULL")>  _
	Public Property monthstamp() As Byte
		Get
			Return Me._monthstamp
		End Get
		Set
			If ((Me._monthstamp = value)  _
						= false) Then
				Me._monthstamp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_oldcasenbr", DbType:="VarChar(12) NOT NULL", CanBeNull:=false)>  _
	Public Property oldcasenbr() As String
		Get
			Return Me._oldcasenbr
		End Get
		Set
			If (String.Equals(Me._oldcasenbr, value) = false) Then
				Me._oldcasenbr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_exacestm", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property exacestm() As String
		Get
			Return Me._exacestm
		End Get
		Set
			If (String.Equals(Me._exacestm, value) = false) Then
				Me._exacestm = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lightcond", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property lightcond() As String
		Get
			Return Me._lightcond
		End Get
		Set
			If (String.Equals(Me._lightcond, value) = false) Then
				Me._lightcond = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lwcircum", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property lwcircum() As String
		Get
			Return Me._lwcircum
		End Get
		Set
			If (String.Equals(Me._lwcircum, value) = false) Then
				Me._lwcircum = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_creserve2", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property creserve2() As String
		Get
			Return Me._creserve2
		End Get
		Set
			If (String.Equals(Me._creserve2, value) = false) Then
				Me._creserve2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_creserve3", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property creserve3() As String
		Get
			Return Me._creserve3
		End Get
		Set
			If (String.Equals(Me._creserve3, value) = false) Then
				Me._creserve3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_labseized", DbType:="Int NOT NULL")>  _
	Public Property labseized() As Integer
		Get
			Return Me._labseized
		End Get
		Set
			If ((Me._labseized = value)  _
						= false) Then
				Me._labseized = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_gangrelat", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property gangrelat() As String
		Get
			Return Me._gangrelat
		End Get
		Set
			If (String.Equals(Me._gangrelat, value) = false) Then
				Me._gangrelat = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ibr_date", DbType:="DateTime")>  _
	Public Property ibr_date() As System.Nullable(Of Date)
		Get
			Return Me._ibr_date
		End Get
		Set
			If (Me._ibr_date.Equals(value) = false) Then
				Me._ibr_date = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ibr_resend", DbType:="TinyInt NOT NULL")>  _
	Public Property ibr_resend() As Byte
		Get
			Return Me._ibr_resend
		End Get
		Set
			If ((Me._ibr_resend = value)  _
						= false) Then
				Me._ibr_resend = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reg_date", DbType:="DateTime")>  _
	Public Property reg_date() As System.Nullable(Of Date)
		Get
			Return Me._reg_date
		End Get
		Set
			If (Me._reg_date.Equals(value) = false) Then
				Me._reg_date = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reg_resend", DbType:="TinyInt NOT NULL")>  _
	Public Property reg_resend() As Byte
		Get
			Return Me._reg_resend
		End Get
		Set
			If ((Me._reg_resend = value)  _
						= false) Then
				Me._reg_resend = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rollcall", DbType:="Bit NOT NULL")>  _
	Public Property rollcall() As Boolean
		Get
			Return Me._rollcall
		End Get
		Set
			If ((Me._rollcall = value)  _
						= false) Then
				Me._rollcall = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_schoolyr", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property schoolyr() As String
		Get
			Return Me._schoolyr
		End Get
		Set
			If (String.Equals(Me._schoolyr, value) = false) Then
				Me._schoolyr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_locacode", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property locacode() As String
		Get
			Return Me._locacode
		End Get
		Set
			If (String.Equals(Me._locacode, value) = false) Then
				Me._locacode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_locadesc", DbType:="VarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property locadesc() As String
		Get
			Return Me._locadesc
		End Get
		Set
			If (String.Equals(Me._locadesc, value) = false) Then
				Me._locadesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_locaphone", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property locaphone() As String
		Get
			Return Me._locaphone
		End Get
		Set
			If (String.Equals(Me._locaphone, value) = false) Then
				Me._locaphone = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_buildarea", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property buildarea() As String
		Get
			Return Me._buildarea
		End Get
		Set
			If (String.Equals(Me._buildarea, value) = false) Then
				Me._buildarea = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_persinvst", DbType:="Char(1) NOT NULL")>  _
	Public Property persinvst() As Char
		Get
			Return Me._persinvst
		End Get
		Set
			If ((Me._persinvst = value)  _
						= false) Then
				Me._persinvst = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_polijuris", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property polijuris() As String
		Get
			Return Me._polijuris
		End Get
		Set
			If (String.Equals(Me._polijuris, value) = false) Then
				Me._polijuris = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_assoccode", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property assoccode() As String
		Get
			Return Me._assoccode
		End Get
		Set
			If (String.Equals(Me._assoccode, value) = false) Then
				Me._assoccode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_locatype", DbType:="Char(1) NOT NULL")>  _
	Public Property locatype() As Char
		Get
			Return Me._locatype
		End Get
		Set
			If ((Me._locatype = value)  _
						= false) Then
				Me._locatype = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_schooltyp", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property schooltyp() As String
		Get
			Return Me._schooltyp
		End Get
		Set
			If (String.Equals(Me._schooltyp, value) = false) Then
				Me._schooltyp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_falsealrm", DbType:="Char(1) NOT NULL")>  _
	Public Property falsealrm() As Char
		Get
			Return Me._falsealrm
		End Get
		Set
			If ((Me._falsealrm = value)  _
						= false) Then
				Me._falsealrm = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_injurdesc", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property injurdesc() As String
		Get
			Return Me._injurdesc
		End Get
		Set
			If (String.Equals(Me._injurdesc, value) = false) Then
				Me._injurdesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_truancrel", DbType:="Char(1) NOT NULL")>  _
	Public Property truancrel() As Char
		Get
			Return Me._truancrel
		End Get
		Set
			If ((Me._truancrel = value)  _
						= false) Then
				Me._truancrel = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_drugtype", DbType:="Char(1) NOT NULL")>  _
	Public Property drugtype() As Char
		Get
			Return Me._drugtype
		End Get
		Set
			If ((Me._drugtype = value)  _
						= false) Then
				Me._drugtype = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hrsrept", DbType:="Char(1) NOT NULL")>  _
	Public Property hrsrept() As Char
		Get
			Return Me._hrsrept
		End Get
		Set
			If ((Me._hrsrept = value)  _
						= false) Then
				Me._hrsrept = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hrsnotdt", DbType:="DateTime")>  _
	Public Property hrsnotdt() As System.Nullable(Of Date)
		Get
			Return Me._hrsnotdt
		End Get
		Set
			If (Me._hrsnotdt.Equals(value) = false) Then
				Me._hrsnotdt = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hrsnotby", DbType:="Int NOT NULL")>  _
	Public Property hrsnotby() As Integer
		Get
			Return Me._hrsnotby
		End Get
		Set
			If ((Me._hrsnotby = value)  _
						= false) Then
				Me._hrsnotby = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sparrace", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property sparrace() As String
		Get
			Return Me._sparrace
		End Get
		Set
			If (String.Equals(Me._sparrace, value) = false) Then
				Me._sparrace = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sparsex", DbType:="Char(1) NOT NULL")>  _
	Public Property sparsex() As Char
		Get
			Return Me._sparsex
		End Get
		Set
			If ((Me._sparsex = value)  _
						= false) Then
				Me._sparsex = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sparage", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property sparage() As String
		Get
			Return Me._sparage
		End Get
		Set
			If (String.Equals(Me._sparage, value) = false) Then
				Me._sparage = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reccheck", DbType:="Char(1) NOT NULL")>  _
	Public Property reccheck() As Char
		Get
			Return Me._reccheck
		End Get
		Set
			If ((Me._reccheck = value)  _
						= false) Then
				Me._reccheck = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_recperinvs", DbType:="Char(1) NOT NULL")>  _
	Public Property recperinvs() As Char
		Get
			Return Me._recperinvs
		End Get
		Set
			If ((Me._recperinvs = value)  _
						= false) Then
				Me._recperinvs = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_recadmrev", DbType:="Char(1) NOT NULL")>  _
	Public Property recadmrev() As Char
		Get
			Return Me._recadmrev
		End Get
		Set
			If ((Me._recadmrev = value)  _
						= false) Then
				Me._recadmrev = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pedinj", DbType:="Char(1) NOT NULL")>  _
	Public Property pedinj() As Char
		Get
			Return Me._pedinj
		End Get
		Set
			If ((Me._pedinj = value)  _
						= false) Then
				Me._pedinj = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_regioncode", DbType:="Char(1) NOT NULL")>  _
	Public Property regioncode() As Char
		Get
			Return Me._regioncode
		End Get
		Set
			If ((Me._regioncode = value)  _
						= false) Then
				Me._regioncode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_plantsecu", DbType:="Char(6) NOT NULL", CanBeNull:=false)>  _
	Public Property plantsecu() As String
		Get
			Return Me._plantsecu
		End Get
		Set
			If (String.Equals(Me._plantsecu, value) = false) Then
				Me._plantsecu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_saorefdate", DbType:="DateTime")>  _
	Public Property saorefdate() As System.Nullable(Of Date)
		Get
			Return Me._saorefdate
		End Get
		Set
			If (Me._saorefdate.Equals(value) = false) Then
				Me._saorefdate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_eeoadate", DbType:="DateTime")>  _
	Public Property eeoadate() As System.Nullable(Of Date)
		Get
			Return Me._eeoadate
		End Get
		Set
			If (Me._eeoadate.Equals(value) = false) Then
				Me._eeoadate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_offcrasslt", DbType:="Char(1) NOT NULL")>  _
	Public Property offcrasslt() As Char
		Get
			Return Me._offcrasslt
		End Get
		Set
			If ((Me._offcrasslt = value)  _
						= false) Then
				Me._offcrasslt = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_perinvrej", DbType:="Char(1) NOT NULL")>  _
	Public Property perinvrej() As Char
		Get
			Return Me._perinvrej
		End Get
		Set
			If ((Me._perinvrej = value)  _
						= false) Then
				Me._perinvrej = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_eeeorej", DbType:="Char(1) NOT NULL")>  _
	Public Property eeeorej() As Char
		Get
			Return Me._eeeorej
		End Get
		Set
			If ((Me._eeeorej = value)  _
						= false) Then
				Me._eeeorej = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_persuadrej", DbType:="Char(1) NOT NULL")>  _
	Public Property persuadrej() As Char
		Get
			Return Me._persuadrej
		End Get
		Set
			If ((Me._persuadrej = value)  _
						= false) Then
				Me._persuadrej = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spardate", DbType:="DateTime")>  _
	Public Property spardate() As System.Nullable(Of Date)
		Get
			Return Me._spardate
		End Get
		Set
			If (Me._spardate.Equals(value) = false) Then
				Me._spardate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sparcaseid", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property sparcaseid() As String
		Get
			Return Me._sparcaseid
		End Get
		Set
			If (String.Equals(Me._sparcaseid, value) = false) Then
				Me._sparcaseid = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sparweap", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property sparweap() As String
		Get
			Return Me._sparweap
		End Get
		Set
			If (String.Equals(Me._sparweap, value) = false) Then
				Me._sparweap = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sparhrsby", DbType:="Int NOT NULL")>  _
	Public Property sparhrsby() As Integer
		Get
			Return Me._sparhrsby
		End Get
		Set
			If ((Me._sparhrsby = value)  _
						= false) Then
				Me._sparhrsby = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_age", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property age() As String
		Get
			Return Me._age
		End Get
		Set
			If (String.Equals(Me._age, value) = false) Then
				Me._age = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_race", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property race() As String
		Get
			Return Me._race
		End Get
		Set
			If (String.Equals(Me._race, value) = false) Then
				Me._race = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sex", DbType:="Char(1) NOT NULL")>  _
	Public Property sex() As Char
		Get
			Return Me._sex
		End Get
		Set
			If ((Me._sex = value)  _
						= false) Then
				Me._sex = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cleryloc", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property cleryloc() As String
		Get
			Return Me._cleryloc
		End Get
		Set
			If (String.Equals(Me._cleryloc, value) = false) Then
				Me._cleryloc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_followup", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property followup() As String
		Get
			Return Me._followup
		End Get
		Set
			If (String.Equals(Me._followup, value) = false) Then
				Me._followup = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_occdtunk", DbType:="Bit NOT NULL")>  _
	Public Property occdtunk() As Boolean
		Get
			Return Me._occdtunk
		End Get
		Set
			If ((Me._occdtunk = value)  _
						= false) Then
				Me._occdtunk = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lwmainid", DbType:="Int NOT NULL")>  _
	Public Property lwmainid() As Integer
		Get
			Return Me._lwmainid
		End Get
		Set
			If ((Me._lwmainid = value)  _
						= false) Then
				Me._lwmainid = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobnamekey", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property mobnamekey() As String
		Get
			Return Me._mobnamekey
		End Get
		Set
			If (String.Equals(Me._mobnamekey, value) = false) Then
				Me._mobnamekey = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobilekey", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property mobilekey() As String
		Get
			Return Me._mobilekey
		End Get
		Set
			If (String.Equals(Me._mobilekey, value) = false) Then
				Me._mobilekey = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobilepkey", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property mobilepkey() As String
		Get
			Return Me._mobilepkey
		End Get
		Set
			If (String.Equals(Me._mobilepkey, value) = false) Then
				Me._mobilepkey = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobstatus", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property mobstatus() As String
		Get
			Return Me._mobstatus
		End Get
		Set
			If (String.Equals(Me._mobstatus, value) = false) Then
				Me._mobstatus = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobstby", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property mobstby() As String
		Get
			Return Me._mobstby
		End Get
		Set
			If (String.Equals(Me._mobstby, value) = false) Then
				Me._mobstby = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobstdate", DbType:="DateTime")>  _
	Public Property mobstdate() As System.Nullable(Of Date)
		Get
			Return Me._mobstdate
		End Get
		Set
			If (Me._mobstdate.Equals(value) = false) Then
				Me._mobstdate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobileflag", DbType:="Char(1) NOT NULL")>  _
	Public Property mobileflag() As Char
		Get
			Return Me._mobileflag
		End Get
		Set
			If ((Me._mobileflag = value)  _
						= false) Then
				Me._mobileflag = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobileid", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property mobileid() As String
		Get
			Return Me._mobileid
		End Get
		Set
			If (String.Equals(Me._mobileid, value) = false) Then
				Me._mobileid = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_moblastrev", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property moblastrev() As String
		Get
			Return Me._moblastrev
		End Get
		Set
			If (String.Equals(Me._moblastrev, value) = false) Then
				Me._moblastrev = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobnotes", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property mobnotes() As String
		Get
			Return Me._mobnotes
		End Get
		Set
			If (String.Equals(Me._mobnotes, value) = false) Then
				Me._mobnotes = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobunitid", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property mobunitid() As String
		Get
			Return Me._mobunitid
		End Get
		Set
			If (String.Equals(Me._mobunitid, value) = false) Then
				Me._mobunitid = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobsupgrp", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property mobsupgrp() As String
		Get
			Return Me._mobsupgrp
		End Get
		Set
			If (String.Equals(Me._mobsupgrp, value) = false) Then
				Me._mobsupgrp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_supervsr2", DbType:="Int NOT NULL")>  _
	Public Property supervsr2() As Integer
		Get
			Return Me._supervsr2
		End Get
		Set
			If ((Me._supervsr2 = value)  _
						= false) Then
				Me._supervsr2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mobstdate2", DbType:="DateTime")>  _
	Public Property mobstdate2() As System.Nullable(Of Date)
		Get
			Return Me._mobstdate2
		End Get
		Set
			If (Me._mobstdate2.Equals(value) = false) Then
				Me._mobstdate2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_suprevlvl", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
	Public Property suprevlvl() As String
		Get
			Return Me._suprevlvl
		End Get
		Set
			If (String.Equals(Me._suprevlvl, value) = false) Then
				Me._suprevlvl = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_clerytyp", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property clerytyp() As String
		Get
			Return Me._clerytyp
		End Get
		Set
			If (String.Equals(Me._clerytyp, value) = false) Then
				Me._clerytyp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_entry1", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property entry1() As String
		Get
			Return Me._entry1
		End Get
		Set
			If (String.Equals(Me._entry1, value) = false) Then
				Me._entry1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_exit1", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property exit1() As String
		Get
			Return Me._exit1
		End Get
		Set
			If (String.Equals(Me._exit1, value) = false) Then
				Me._exit1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_safecode", DbType:="Char(4) NOT NULL", CanBeNull:=false)>  _
	Public Property safecode() As String
		Get
			Return Me._safecode
		End Get
		Set
			If (String.Equals(Me._safecode, value) = false) Then
				Me._safecode = value
			End If
		End Set
	End Property
End Class
